FROM node:alpine

# Install app dependencies
RUN apk update && apk upgrade && apk add git

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN apk add --no-cache make gcc g++ python && \
  npm install --production --silent && \
  apk del make gcc g++ python

COPY . /usr/src/app/
RUN npm install

ENV HOST 0.0.0.0
EXPOSE 3000:3000

# start command
CMD [ "npm", "start", "dev" ]
